version: "3.9"

services:
  db:
    container_name: mongo-admin
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=cyber-system
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks: 
      - mongodb-admin-network
    ports:
      - '27017:27017'
    volumes: 
      - ./data:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - db
    networks: 
      - mongodb-admin-network
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - '8081:8081'
    volumes: 
      - ./data:/data/db      

networks:
  mongodb-admin-network:
    driver: bridge